# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ibrahimcancode/flyrank-ml-internship/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [1]:
from huggingface_hub import login, whoami

from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

login(token=HF_TOKEN)

whoami()

{'type': 'user',
 'id': '6a68b89d92af67ac9865e06f',
 'name': 'ibrahimcancode',
 'fullname': 'ibrahim',
 'isPro': False,
 'avatarUrl': '/avatars/88873575abe45db6741bf45ed03632ca.svg',
 'orgs': [],
 'auth': {'type': 'access_token',
  'accessToken': {'displayName': 'internship flyrank ml5',
   'role': 'fineGrained',
   'createdAt': '2026-08-01T15:14:46.415Z',
   'fineGrained': {'canReadGatedRepos': True,
    'global': [],
    'scoped': [{'entity': {'_id': '6a68b89d92af67ac9865e06f',
       'type': 'user',
       'name': 'ibrahimcancode'},
      'permissions': ['repo.content.read']}]}}}}

In [2]:
from huggingface_hub import hf_hub_download
import pandas as pd

file_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="fact_content_daily_performance_sample.parquet",
    repo_type="dataset"
)

df = pd.read_parquet(file_path)

df.head()

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2026-06-01,client_3ffa76342f366962,content_1a6296faee432dae,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
1,2026-06-01,client_3ffa76342f366962,content_73f21e612565035a,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
2,2026-06-01,client_3ffa76342f366962,content_5a5be514ff559598,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
3,2026-06-01,client_3ffa76342f366962,content_05b377d0c8a5cfd8,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
4,2026-06-01,client_3ffa76342f366962,content_dc34c661d63e55a9,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06

In [3]:
df.shape

(11694072, 31)

In [4]:
df["ctr"] = df["gsc_clicks"] / (df["gsc_impressions"] + 1)

df[["gsc_impressions", "gsc_clicks", "ctr"]].head()

   gsc_impressions  gsc_clicks  ctr
0                0           0  0.0
1                0           0  0.0
2                0           0  0.0
3                0           0  0.0
4                0           0  0.0

In [5]:
df["gsc_impressions"].describe()

count    1.169407e+07
mean     1.848756e+01
std      1.572285e+02
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      3.000000e+00
max      2.458260e+05
Name: gsc_impressions, dtype: float64

In [6]:
(df["gsc_impressions"] > 0).sum()

np.int64(3878937)

In [7]:
df[df["gsc_impressions"] > 0][
    ["gsc_impressions", "gsc_clicks", "ctr"]
].head(20)

     gsc_impressions  gsc_clicks  ctr
117                1           0  0.0
193                1           0  0.0
232                8           0  0.0
243                1           0  0.0
286                1           0  0.0
289                2           0  0.0
356                1           0  0.0
393                1           0  0.0
397                1           0  0.0
402                3           0  0.0
410                3           0  0.0
415                2           0  0.0
463                3           0  0.0
465                2           0  0.0
478                4           0  0.0
484                1           0  0.0
502                1           0  0.0
532                1           0  0.0
606                1           0  0.0
621                1           0  0.0

In [8]:
signal_df = df[df["gsc_impressions"] > 0].copy()

signal_df.shape

(3878937, 32)

In [9]:
signal_df["ctr"] = (
    signal_df["gsc_clicks"] /
    signal_df["gsc_impressions"]
)

In [10]:
signal_df["impression_bucket"] = pd.qcut(
    signal_df["gsc_impressions"],
    q=4,
    duplicates="drop"
)

impression_check = (
    signal_df.groupby("impression_bucket", observed=True)
    .agg(
        n=("gsc_impressions", "count"),
        avg_clicks=("gsc_clicks", "mean"),
        avg_ctr=("ctr", "mean")
    )
    .reset_index()
)

impression_check

  impression_bucket        n  avg_clicks   avg_ctr
0      (0.999, 3.0]  1106560    0.007177  0.004256
1       (3.0, 10.0]   895781    0.039013  0.006576
2      (10.0, 35.0]   917980    0.091185  0.004524
3  (35.0, 245826.0]   958616    1.129255  0.004411

In [11]:
signal_df["ctr_bucket"] = pd.cut(
    signal_df["ctr"],
    bins=[
        -0.001,
        0.01,
        0.05,
        0.20,
        1.0
    ],
    labels=[
        "Very Low CTR",
        "Low CTR",
        "Medium CTR",
        "High CTR"
    ]
)

ctr_check = (
    signal_df.groupby("ctr_bucket", observed=True)
    .agg(
        n=("ctr", "count"),
        avg_impressions=("gsc_impressions", "mean"),
        avg_clicks=("gsc_clicks", "mean")
    )
    .reset_index()
)

ctr_check

     ctr_bucket        n  avg_impressions  avg_clicks
0  Very Low CTR  3605749        53.119789    0.097944
1       Low CTR   197510       113.247841    2.129016
2    Medium CTR    58489        28.698029    1.998923
3      High CTR    17189        35.612659   18.531619

In [12]:
df.shape

(11694072, 32)

In [13]:
import pandas as pd
import numpy as np
import os
from huggingface_hub import hf_hub_download

# Load dataset
file_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="fact_content_daily_performance_sample.parquet",
    repo_type="dataset"
)

df = pd.read_parquet(file_path)

print("Dataset shape:", df.shape)

df.head()

Dataset shape: (11694072, 31)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2026-06-01,client_3ffa76342f366962,content_1a6296faee432dae,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
1,2026-06-01,client_3ffa76342f366962,content_73f21e612565035a,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
2,2026-06-01,client_3ffa76342f366962,content_5a5be514ff559598,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
3,2026-06-01,client_3ffa76342f366962,content_05b377d0c8a5cfd8,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
4,2026-06-01,client_3ffa76342f366962,content_dc34c661d63e55a9,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06

In [1]:
import pandas as pd
import numpy as np
import os
from huggingface_hub import hf_hub_download

# Load FlyRank dataset

file_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="fact_content_daily_performance_sample.parquet",
    repo_type="dataset"
)

df = pd.read_parquet(file_path)

print("Dataset loaded")
print("Shape:", df.shape)

df.head()

Dataset loaded
Shape: (11694072, 31)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2026-06-01,client_3ffa76342f366962,content_1a6296faee432dae,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
1,2026-06-01,client_3ffa76342f366962,content_73f21e612565035a,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
2,2026-06-01,client_3ffa76342f366962,content_5a5be514ff559598,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
3,2026-06-01,client_3ffa76342f366962,content_05b377d0c8a5cfd8,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
4,2026-06-01,client_3ffa76342f366962,content_dc34c661d63e55a9,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06

In [2]:
df.shape

(11694072, 31)

In [3]:
import pandas as pd
import numpy as np
import os
from huggingface_hub import hf_hub_download

In [4]:
from google.colab import userdata
from huggingface_hub import login

HF_TOKEN = userdata.get("HF_TOKEN")

login(token=HF_TOKEN)

In [5]:
file_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="fact_content_daily_performance_sample.parquet",
    repo_type="dataset"
)

df = pd.read_parquet(file_path)

print(df.shape)

df.head()

(11694072, 31)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2026-06-01,client_3ffa76342f366962,content_1a6296faee432dae,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
1,2026-06-01,client_3ffa76342f366962,content_73f21e612565035a,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
2,2026-06-01,client_3ffa76342f366962,content_5a5be514ff559598,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
3,2026-06-01,client_3ffa76342f366962,content_05b377d0c8a5cfd8,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06
4,2026-06-01,client_3ffa76342f366962,content_dc34c661d63e55a9,True,True,False,False,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-06

In [6]:
df.shape

(11694072, 31)

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

## My Rule and Reason Codes

### Rule

This baseline prioritizes content that has search visibility but weak click efficiency.

The two signals used are:

1. **gsc_impressions**
   - Measures search visibility.
   - Higher impressions indicate content is being shown to users.

2. **CTR**
   - Calculated as gsc_clicks / gsc_impressions.
   - Measures how effectively impressions convert into clicks.

### Signal Checks

#### Signal 1: gsc_impressions

Verdict: **CONFIRMED**

Observed bucket analysis shows that higher impression groups contain higher average clicks, making impressions a useful prioritization signal.

#### Signal 2: CTR

Verdict: **CONFIRMED**

Observed CTR buckets separate pages with weak and strong click efficiency. Pages with impressions and low CTR are potential review candidates.

### Baseline Decision Rule

If:
- impressions are high
- CTR is low

Then:

Reason code:
`VISIBLE_LOW_CTR`

Action:
`REVIEW_FIRST`

Otherwise:

Reason code:
`NO_ACTION`

Action:
`MONITOR`

This rule is a directional decision-support baseline and does not claim causality.

In [7]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# Create CTR signal
signal_df = df[df["gsc_impressions"] > 0].copy()

signal_df["ctr"] = (
    signal_df["gsc_clicks"] /
    signal_df["gsc_impressions"]
)


# ---------------------------
# Signal 1: Impressions Check
# ---------------------------

signal_df["impression_bucket"] = pd.qcut(
    signal_df["gsc_impressions"],
    q=4,
    duplicates="drop"
)

impression_check = (
    signal_df.groupby("impression_bucket", observed=True)
    .agg(
        n=("gsc_impressions", "count"),
        avg_clicks=("gsc_clicks", "mean"),
        avg_ctr=("ctr", "mean")
    )
    .reset_index()
)

print("Impressions Signal Check")
display(impression_check)


# ---------------------------
# Signal 2: CTR Check
# ---------------------------

signal_df["ctr_bucket"] = pd.cut(
    signal_df["ctr"],
    bins=[
        -0.001,
        0.01,
        0.05,
        0.20,
        1.0
    ],
    labels=[
        "Very Low CTR",
        "Low CTR",
        "Medium CTR",
        "High CTR"
    ]
)

ctr_check = (
    signal_df.groupby("ctr_bucket", observed=True)
    .agg(
        n=("ctr", "count"),
        avg_impressions=("gsc_impressions", "mean"),
        avg_clicks=("gsc_clicks", "mean")
    )
    .reset_index()
)

print("CTR Signal Check")
display(ctr_check)

Impressions Signal Check

  impression_bucket        n  avg_clicks   avg_ctr
0      (0.999, 3.0]  1106560    0.007177  0.004256
1       (3.0, 10.0]   895781    0.039013  0.006576
2      (10.0, 35.0]   917980    0.091185  0.004524
3  (35.0, 245826.0]   958616    1.129255  0.004411

CTR Signal Check

     ctr_bucket        n  avg_impressions  avg_clicks
0  Very Low CTR  3605749        53.119789    0.097944
1       Low CTR   197510       113.247841    2.129016
2    Medium CTR    58489        28.698029    1.998923
3      High CTR    17189        35.612659   18.531619

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

## Build the Ranked Queue

The baseline score prioritizes pages that have search visibility but weak click efficiency.

Signals used:

- `gsc_impressions`: measures how visible a page is in search.
- CTR (`gsc_clicks / gsc_impressions`): measures how effectively impressions become clicks.

Scoring rule:

- Higher impressions increase priority.
- Lower CTR increases opportunity score.

Reason codes:

- `VISIBLE_LOW_CTR`: page has visibility but weak click efficiency.
- `NO_ACTION`: page does not meet the review threshold.

Actions:

- `REVIEW_FIRST`
- `MONITOR`

This baseline is directional decision-support and does not claim causality.

In [8]:
import os
import numpy as np

# Only keep needed columns
score_df = df[["gsc_impressions", "gsc_clicks"]].copy()

# CTR
score_df["ctr"] = (
    score_df["gsc_clicks"] /
    (score_df["gsc_impressions"] + 1)
)

# Keep only likely candidates
score_df = score_df[
    (score_df["gsc_impressions"] >= 35)
]

# Normalize impressions
score_df["impression_score"] = (
    score_df["gsc_impressions"] /
    score_df["gsc_impressions"].max()
)

# Opportunity score
score_df["ctr_opportunity"] = (
    1 - score_df["ctr"].clip(0, 1)
)

# Final score
score_df["score"] = (
    0.6 * score_df["impression_score"] +
    0.4 * score_df["ctr_opportunity"]
)

# Reason code
score_df["reason_code"] = np.where(
    score_df["ctr"] < 0.01,
    "VISIBLE_LOW_CTR",
    "NO_ACTION"
)

# Action
score_df["action"] = np.where(
    score_df["reason_code"] == "VISIBLE_LOW_CTR",
    "REVIEW_FIRST",
    "MONITOR"
)

# Keep only review candidates
score_df = score_df[
    score_df["reason_code"] == "VISIBLE_LOW_CTR"
]

# Sort only candidates
score_df = score_df.sort_values(
    "score",
    ascending=False
)

# Rank
score_df["rank"] = range(1, len(score_df) + 1)

os.makedirs("work/outputs", exist_ok=True)

score_df.to_csv(
    "work/outputs/baseline_action_score.csv",
    index=False
)

score_df.head(20)

,gsc_impressions,gsc_clicks,ctr,impression_score,ctr_opportunity,score,reason_code,action,rank
2800173,245826,890,0.003620,1.000000,0.996380,0.998552,VISIBLE_LOW_CTR,REVIEW_FIRST,1
11132195,49373,173,0.003504,0.200845,0.996496,0.519106,VISIBLE_LOW_CTR,REVIEW_FIRST,2
10705037,48953,114,0.002329,0.199137,0.997671,0.518551,VISIBLE_LOW_CTR,REVIEW_FIRST,3
10996119,48990,189,0.003858,0.199287,0.996142,0.518029,VISIBLE_LOW_CTR,REVIEW_FIRST,4
3742077,46220,81,0.001752,0.188019,0.998248,0.512111,VISIBLE_LOW_CTR,REVIEW_FIRST,5
11688634,45890,329,0.007169,0.186677,0.992831,0.509138,VISIBLE_LOW_CTR,REVIEW_FIRST,6
10871723,42474,107,0.002519,0.172781,0.997481,0.502661,VISIBLE_LOW_CTR,REVIEW_FIRST,7
10032532,41051,129,0.003142,0.166992,0.996858,0.498938,VISIBLE_LOW_CTR,REVIEW_FIRST,8
11378338,35560,313,0.008802,0.144655,0.991198,0.483272,VISIBLE_LOW_CTR,REVIEW_FIRST,9
9280128,30645,50,0.001632,0.124661,0.998368,0.474144,VISIBLE_LOW_CTR,REVIEW_FIRST,10
9907816,28952,134,0.004628,0.117774,0.995372,0.468813,VISIBLE_LOW_CTR,REVIEW_FIRST,11
9570454,28945,182,0.006288,0.117746,0.993712,0.468133,VISIBLE_LOW_CTR,REVIEW_FIRST,12
73504,27135,175,0.006449,0.110383,0.993551,0.463650,VISIBLE_LOW_CTR,REVIEW_FIRST,13
978730,26241,70,0.002667,0.106746,0.997333,0.462981,VISIBLE_LOW_CTR,REVIEW_FIRST,14
9907805,26038,61,0.002343,0.105920,0.997657,0.462615,VISIBLE_LOW_CTR,REVIEW_FIRST,15
8645168,25191,0,0.000000,0.102475,1.000000,0.461485,VISIBLE_LOW_CTR,REVIEW_FIRST,16
3836518,25111,3,0.000119,0.102149,0.999881,0.461242,VISIBLE_LOW_CTR,REVIEW_FIRST,17
2237447,25505,173,0.006783,0.103752,0.993217,0.459538,VISIBLE_LOW_CTR,REVIEW_FIRST,18
6705923,24435,49,0.002005,0.099400,0.997995,0.458838,VISIBLE_LOW_CTR,REVIEW_FIRST,19
2292644,25186,175,0.006948,0.102455,0.993052,0.458694,VISIBLE_LOW_CTR,REVIEW_FIRST,20

In [ ]:
%whos

Variable           Type         Data/Info
-----------------------------------------
HF_TOKEN           str          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
ctr_check          DataFrame         ctr_bucket        n <...>    35.612659   18.531619
df                 DataFrame

In [1]:
import pandas as pd
import numpy as np
import os
from huggingface_hub import hf_hub_download

In [2]:
from huggingface_hub import hf_hub_download

file_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="fact_content_daily_performance_sample.parquet",
    repo_type="dataset"
)

df = pd.read_parquet(file_path)

print(df.shape)

(11694072, 31)

In [3]:
import os

os.path.exists("work/outputs/baseline_action_score.csv")

True

In [4]:
baseline = pd.read_csv("work/outputs/baseline_action_score.csv")

baseline.head(20)

,gsc_impressions,gsc_clicks,ctr,impression_score,ctr_opportunity,score,reason_code,action,rank
0,245826,890,0.003620,1.000000,0.996380,0.998552,VISIBLE_LOW_CTR,REVIEW_FIRST,1
1,49373,173,0.003504,0.200845,0.996496,0.519106,VISIBLE_LOW_CTR,REVIEW_FIRST,2
2,48953,114,0.002329,0.199137,0.997671,0.518551,VISIBLE_LOW_CTR,REVIEW_FIRST,3
3,48990,189,0.003858,0.199287,0.996142,0.518029,VISIBLE_LOW_CTR,REVIEW_FIRST,4
4,46220,81,0.001752,0.188019,0.998248,0.512111,VISIBLE_LOW_CTR,REVIEW_FIRST,5
5,45890,329,0.007169,0.186677,0.992831,0.509138,VISIBLE_LOW_CTR,REVIEW_FIRST,6
6,42474,107,0.002519,0.172781,0.997481,0.502661,VISIBLE_LOW_CTR,REVIEW_FIRST,7
7,41051,129,0.003142,0.166992,0.996858,0.498938,VISIBLE_LOW_CTR,REVIEW_FIRST,8
8,35560,313,0.008802,0.144655,0.991198,0.483272,VISIBLE_LOW_CTR,REVIEW_FIRST,9
9,30645,50,0.001632,0.124661,0.998368,0.474144,VISIBLE_LOW_CTR,REVIEW_FIRST,10
10,28952,134,0.004628,0.117774,0.995372,0.468813,VISIBLE_LOW_CTR,REVIEW_FIRST,11
11,28945,182,0.006288,0.117746,0.993712,0.468133,VISIBLE_LOW_CTR,REVIEW_FIRST,12
12,27135,175,0.006449,0.110383,0.993551,0.463650,VISIBLE_LOW_CTR,REVIEW_FIRST,13
13,26241,70,0.002667,0.106746,0.997333,0.462981,VISIBLE_LOW_CTR,REVIEW_FIRST,14
14,26038,61,0.002343,0.105920,0.997657,0.462615,VISIBLE_LOW_CTR,REVIEW_FIRST,15
15,25191,0,0.000000,0.102475,1.000000,0.461485,VISIBLE_LOW_CTR,REVIEW_FIRST,16
16,25111,3,0.000119,0.102149,0.999881,0.461242,VISIBLE_LOW_CTR,REVIEW_FIRST,17
17,25505,173,0.006783,0.103752,0.993217,0.459538,VISIBLE_LOW_CTR,REVIEW_FIRST,18
18,24435,49,0.002005,0.099400,0.997995,0.458838,VISIBLE_LOW_CTR,REVIEW_FIRST,19
19,25186,175,0.006948,0.102455,0.993052,0.458694,VISIBLE_LOW_CTR,REVIEW_FIRST,20

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

## Top-20 Review

The ranked queue was reviewed manually to understand whether the recommended actions appear reasonable.

Confidence is based on the observed signals only. These recommendations are directional decision-support and could change with additional information such as page quality, content intent, seasonality, or business context.

| Rank | Action | Reason Code | Confidence | What would make it wrong? |
|------|--------|-------------|------------|----------------------------|
|1|REVIEW_FIRST|VISIBLE_LOW_CTR|High|If the page intentionally targets awareness rather than clicks or the query intent limits CTR.|
|2|REVIEW_FIRST|VISIBLE_LOW_CTR|High|If impressions are driven by irrelevant queries that are not expected to generate clicks.|
|3|REVIEW_FIRST|VISIBLE_LOW_CTR|High|If the page recently changed and CTR has not stabilized.|
|4|REVIEW_FIRST|VISIBLE_LOW_CTR|High|If seasonal search behavior temporarily reduced CTR.|
|5|REVIEW_FIRST|VISIBLE_LOW_CTR|High|If rich results or SERP features reduce click opportunities.|
|6|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If the page already has ongoing optimization work.|
|7|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If search intent does not match the page purpose.|
|8|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If measurement errors affect click reporting.|
|9|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If low CTR is expected for informational queries.|
|10|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If external events temporarily changed user behavior.|
|11|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If metadata was recently updated and results are delayed.|
|12|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If search demand is unusually volatile.|
|13|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If ranking positions recently changed.|
|14|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If the page serves a niche audience with naturally low CTR.|
|15|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If impressions include many low-intent searches.|
|16|REVIEW_FIRST|VISIBLE_LOW_CTR|High|Zero clicks may reflect temporary data rather than poor content.|
|17|REVIEW_FIRST|VISIBLE_LOW_CTR|High|Very few clicks may be caused by tracking limitations.|
|18|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If search snippets already match user intent well.|
|19|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If competitor changes temporarily affected CTR.|
|20|REVIEW_FIRST|VISIBLE_LOW_CTR|Medium|If future optimization already addresses the issue.|

In [6]:
import pandas as pd

top20 = pd.read_csv(
    "work/outputs/baseline_action_score.csv"
).head(20)

top20[
    [
        "rank",
        "score",
        "reason_code",
        "action",
        "gsc_impressions",
        "gsc_clicks",
        "ctr"
    ]
]

,rank,score,reason_code,action,gsc_impressions,gsc_clicks,ctr
0,1,0.998552,VISIBLE_LOW_CTR,REVIEW_FIRST,245826,890,0.003620
1,2,0.519106,VISIBLE_LOW_CTR,REVIEW_FIRST,49373,173,0.003504
2,3,0.518551,VISIBLE_LOW_CTR,REVIEW_FIRST,48953,114,0.002329
3,4,0.518029,VISIBLE_LOW_CTR,REVIEW_FIRST,48990,189,0.003858
4,5,0.512111,VISIBLE_LOW_CTR,REVIEW_FIRST,46220,81,0.001752
5,6,0.509138,VISIBLE_LOW_CTR,REVIEW_FIRST,45890,329,0.007169
6,7,0.502661,VISIBLE_LOW_CTR,REVIEW_FIRST,42474,107,0.002519
7,8,0.498938,VISIBLE_LOW_CTR,REVIEW_FIRST,41051,129,0.003142
8,9,0.483272,VISIBLE_LOW_CTR,REVIEW_FIRST,35560,313,0.008802
9,10,0.474144,VISIBLE_LOW_CTR,REVIEW_FIRST,30645,50,0.001632
10,11,0.468813,VISIBLE_LOW_CTR,REVIEW_FIRST,28952,134,0.004628
11,12,0.468133,VISIBLE_LOW_CTR,REVIEW_FIRST,28945,182,0.006288
12,13,0.463650,VISIBLE_LOW_CTR,REVIEW_FIRST,27135,175,0.006449
13,14,0.462981,VISIBLE_LOW_CTR,REVIEW_FIRST,26241,70,0.002667
14,15,0.462615,VISIBLE_LOW_CTR,REVIEW_FIRST,26038,61,0.002343
15,16,0.461485,VISIBLE_LOW_CTR,REVIEW_FIRST,25191,0,0.000000
16,17,0.461242,VISIBLE_LOW_CTR,REVIEW_FIRST,25111,3,0.000119
17,18,0.459538,VISIBLE_LOW_CTR,REVIEW_FIRST,25505,173,0.006783
18,19,0.458838,VISIBLE_LOW_CTR,REVIEW_FIRST,24435,49,0.002005
19,20,0.458694,VISIBLE_LOW_CTR,REVIEW_FIRST,25186,175,0.006948

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

## Weak Picks + Leakage Check

### Weak Picks

Some ranked pages may still be false positives.

Possible reasons include:

- High impressions may be driven by informational queries where lower CTR is expected.
- Some pages may have recently been published or updated, so CTR has not stabilized.
- Seasonal search behavior can temporarily reduce CTR without indicating a content problem.
- SERP features (featured snippets, AI answers, knowledge panels, etc.) may reduce clicks even when a page performs well.

These observations mean the baseline should be treated as directional decision-support rather than a final recommendation.

### Leakage Check

The baseline intentionally avoids future information and product-generated flags.

Excluded from scoring:

- Future performance windows
- Label-derived columns
- Product recommendation flags
- Client-identifying information

The rule only uses:

- `gsc_impressions`
- `gsc_clicks`
- Calculated CTR

These signals are available before making the recommendation, reducing the risk of data leakage.

In [8]:
import pandas as pd

baseline = pd.read_csv("work/outputs/baseline_action_score.csv")

used_columns = [
    "gsc_impressions",
    "gsc_clicks"
]

print("Columns used for scoring:")
print(used_columns)

print("\nTotal review candidates:")
print(len(baseline))

print("\nReason Code Distribution")
print(baseline["reason_code"].value_counts())

print("\nAction Distribution")
print(baseline["action"].value_counts())

print("\nLeakage Check:")
print("- No future-window features used")
print("- No product flags used")
print("- No client identifiers used")
print("- Only pre-prediction signals were included")

Columns used for scoring:
['gsc_impressions', 'gsc_clicks']

Total review candidates:
813401

Reason Code Distribution
reason_code
VISIBLE_LOW_CTR    813401
Name: count, dtype: int64

Action Distribution
action
REVIEW_FIRST    813401
Name: count, dtype: int64

Leakage Check:
- No future-window features used
- No product flags used
- No client identifiers used
- Only pre-prediction signals were included

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.